
train_dataloader:
  dataset:
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: PolyRandomfilp}
        - {type: PolyAffine, output_size: [512,512],mode: 'train'}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}

  collate_fn:
    type: BatchImageCollateFunction
    scale_ori : 512
    scale_ori_repeat: null
    stop_epoch: 200 # epoch in [72, ~) stop `multiscales`

  shuffle: True
  total_batch_size: 32 # total batch size equals to 32 (4 * 8)
  num_workers: 4


val_dataloader:
  dataset:
    transforms:
      ops:
        - {type: PolyAffine, output_size: [512,512],mode: 'test'}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
  shuffle: False
  total_batch_size: 64
  num_workers: 4
