task: detection

model: ContourFormer
criterion: Criterion
postprocessor: ContourPostProcessor

use_focal_loss: True
eval_spatial_size: [512, 512] # h w

ContourFormer:
  backbone: HGNetv2
  encoder: HybridEncoder
  decoder: ContourTransformer

HGNetv2:
  pretrained: True
  local_model_dir: weight/hgnetv2/

HybridEncoder:
  in_channels: [512, 1024, 2048]
  feat_strides: [8, 16, 32]

  # intra
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.
  enc_act: 'gelu'
  
  # cross
  expansion: 1.0
  depth_mult: 1
  act: 'silu'


ContourTransformer:
  feat_channels: [256, 256, 256]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  num_levels: 3

  num_layers: 6
  num_queries: 300

  num_points: [3, 6, 3] # [4, 4, 4] [3, 6, 3]


ContourPostProcessor:
  num_top_queries: 300


Criterion:
  weight_dict: {loss_vfl: 1, loss_pts_l1: 5, loss_bbox: 5, loss_giou: 2}
  losses: ['vfl', 'ptsL1']
  alpha: 0.75
  gamma: 2.0

  matcher:
    type: ContourHungarianMatcher
    weight_dict: {cost_class: 2, cost_bbox: 5, cost_giou: 5, cost_pts: 5}
    alpha: 0.25
    gamma: 2.0